### ISSUE TITLE
pdfファイルの移動と利用していないpdfファイルの削除

### ISSUE THREAD

**Issue by zEttOn86** [simizlab/simizlab-homepage#11]
a79faf7a83671cfbe35c33cd0a3b4df1798966d1 において，`static` 以下に存在した `csv` フォルダが `content/source` 以下に移動しました．

なので，同様に `pdf` フォルダの移動もお願いしたいです．

またその際に利用していない以下のファイルの削除をお願いします．

- `Reviewed proceedings of international conference.pdf`
- `Invited talks_tutorial_symposium.pdf`
- `Books & Reviewed journal papers.pdf`
- `Awards & Patents.pdf`

**Comment by saito3** [comment]
@zEttOn86 すみません、csvファイルをサイトにアップロードしたくなかったので `content/source` に移動してみたのですが、よく見たら `public/source` にそのままコピーされてますね。
csvファイルの適切な置き場ってどこなんでしょう？

**Comment by zEttOn86** [comment]
[このサイト](https://discourse.gohugo.io/t/ignore-a-directory/8880)によると
```
ignoreFIles = ["source/csv/.*"]
```
を追加するとビルドしたときに`public`に`content/source/csv`以下を吐き出さないようにできるようです．そのため，その修正を行いました．

pdfはリンクの関係からアップロードは必要であるため，`static`フォルダに戻しました．
